/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package consolidandounidad2;

/**
 *
 * @author EduardoPC
 */
public class Unidad2 extends javax.swing.JFrame {

    /**
     * Creates new form Unidad2
     */
    
    Ejercicio1 VEjercicio1 = new Ejercicio1();
    Ejercicio2 VEjercicio2 = new Ejercicio2();
    Ejercicio3 VEjercicio3 = new Ejercicio3();
    public Unidad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AbrirEjercicio1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AbrirEjercicio2 = new javax.swing.JMenuItem();
        ejercicio3 = new javax.swing.JMenu();
        AbrirEjercicio3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Ejercicio1");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        AbrirEjercicio1.setText("Ejercicio1");
        AbrirEjercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirEjercicio1ActionPerformed(evt);
            }
        });
        jMenu1.add(AbrirEjercicio1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ejercicio2");

        AbrirEjercicio2.setText("Ejercicio2");
        AbrirEjercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirEjercicio2ActionPerformed(evt);
            }
        });
        jMenu2.add(AbrirEjercicio2);

        jMenuBar1.add(jMenu2);

        ejercicio3.setText("Ejercicio3");

        AbrirEjercicio3.setText("Ejercicio3");
        AbrirEjercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirEjercicio3ActionPerformed(evt);
            }
        });
        ejercicio3.add(AbrirEjercicio3);

        jMenuBar1.add(ejercicio3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void AbrirEjercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirEjercicio1ActionPerformed
        // TODO add your handling code h
        this.escritorio.add(this.VEjercicio1);
        this.VEjercicio1.setVisible(true);
    }//GEN-LAST:event_AbrirEjercicio1ActionPerformed

    private void AbrirEjercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirEjercicio2ActionPerformed
        // TODO add your handling code here:
        this.escritorio.add(this.VEjercicio2);
        this.VEjercicio2.setVisible(true);
    }//GEN-LAST:event_AbrirEjercicio2ActionPerformed

    private void AbrirEjercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirEjercicio3ActionPerformed
        // TODO add your handling code here:
        this.escritorio.add(this.VEjercicio3);
        this.VEjercicio3.setVisible(true);
    }//GEN-LAST:event_AbrirEjercicio3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unidad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unidad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unidad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unidad2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Unidad2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirEjercicio1;
    private javax.swing.JMenuItem AbrirEjercicio2;
    private javax.swing.JMenuItem AbrirEjercicio3;
    private javax.swing.JMenu ejercicio3;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
